import Head from "next/head";

import { Stage } from "@/components/stage";
import { HowItWorks } from "../components/howItWorks";

export default function Home() {
  return (
    <>
      <Head>
        <title>PHR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ padding: "0 0 200px 0" }}>
        <Stage />

        <HowItWorks />
      </main>
    </>
  );
}
