import { Button, Typography } from "antd";
import Head from "next/head";
import Link from "next/link";

import styles from "@/styles/index.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>PHR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.container}>
          <Typography.Title className={styles.headline}>
            Pusher
          </Typography.Title>

          <Link href="./console">
            <Button className={styles.navButton} type="primary">
              Open Console
            </Button>
          </Link>
        </div>
      </main>
    </>
  );
}
