name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        name: Install
        with:
          version: 8
          run_install: true

      - name: Build
        env:
          NEXTAUTH_GITHUB_ID: ${{ secrets.NEXTAUTH_GITHUB_ID }}
          NEXTAUTH_GITHUB_SECRET: ${{ secrets.NEXTAUTH_GITHUB_SECRET }}
          NEXT_PUBLIC_WEBSOCKET_KEY: ${{ secrets.NEXT_PUBLIC_WEBSOCKET_KEY }}
          TABLE_NAME: ${{ secrets.TABLE_NAME }}
          USER_INDEX_NAME: ${{ secrets.USER_INDEX_NAME }}
        run: pnpm run build

      - name: Deploy AWS
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          RESEND_TOKEN: ${{ secrets.RESEND_TOKEN }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          TABLE_NAME: ${{ secrets.TABLE_NAME }}
          RUNNER_FUNCTION_NAME: ${{ secrets.RUNNER_FUNCTION_NAME }}
          INTERVAL_INDEX_NAME: ${{ secrets.INTERVAL_INDEX_NAME }}
          USER_INDEX_NAME: ${{ secrets.USER_INDEX_NAME }}
          REGION: ${{ secrets.REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NEXTAUTH_GITHUB_ID: ${{ secrets.NEXTAUTH_GITHUB_ID }}
          NEXTAUTH_GITHUB_SECRET: ${{ secrets.NEXTAUTH_GITHUB_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          WEBSOCKET_APP_ID: ${{ secrets.WEBSOCKET_APP_ID }}
          WEBSOCKET_SECRET: ${{ secrets.WEBSOCKET_SECRET }}
          NEXT_PUBLIC_WEBSOCKET_KEY: ${{ secrets.NEXT_PUBLIC_WEBSOCKET_KEY }}
          CHROMIUM_URL: ${{ vars.CHROMIUM_URL }}
        run: pnpm run --filter @pusher/aws deploy -- --require-approval=never

      - name: Setup
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          MAC_FFMPEG_URL: ${{ vars.MAC_FFMPEG_URL }}
          LINUX_FFMPEG_URL: ${{ vars.LINUX_FFMPEG_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: pnpm run setup
