name: Deploy Preview
on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Create or Update Comment
        id: pr-comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            const { repository, pull_request: { number } } = context.payload;

            const owner = repository.owner.login;
            const repo = repository.name;

            const url = '${{ steps.deploy.outputs.url }}';

            const prefix = ":rocket: **Preview Deployment:**";

            const { data: comments } = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: number,
            });

            const comment = comments.find(({ body }) => body.includes(prefix));

            const body = `${prefix} [${url.replace("https://", "")}](${url})`;

            if (!comment) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: number,
                body
              });
            } else {
              await github.rest.issues.updateComment({
                owner,
                repo,
                comment_id: comment.id,
                body
              });
            }
